(in-package #:nshell.presentation)
(defun compute-suggestion (history input)
  (nshell.application:history-suggestion history input))
(defun accept-suggestion (input suggestion)
  (concatenate 'string input suggestion))
