(in-package #:nshell.presentation)
(defun render-completions (candidates)
  (when candidates
    (format t "~%~{~a  ~}" (mapcar #'nshell.domain.completion:candidate-text (subseq candidates 0 (min 8 (length candidates)))))
    (format t "~%")))
(defun cycle-completion (candidates current)
  (let ((n (length candidates)))
    (if (zerop n) 0 (mod (1+ current) n))))
(defun apply-completion (input candidate)
  (nshell.domain.completion:candidate-text candidate))
