(in-package #:nshell.presentation)
(defstruct (highlight-span (:constructor make-highlight-span (start end role)))
  (start 0 :type integer :read-only t)
  (end 0 :type integer :read-only t)
  (role :command :type keyword :read-only t))
(defun highlight-line (input)
  (multiple-value-bind (tokens cursor incomplete)
      (nshell.domain.parsing:tokenize input)
    (declare (ignore cursor incomplete))
    (mapcar (lambda (tok)
              (make-highlight-span
               (nshell.domain.parsing:token-start tok)
               (nshell.domain.parsing:token-end tok)
               (case (nshell.domain.parsing:token-type tok)
                 (:word :command)
                 (:pipe :operator)
                 (:redirect :operator)
                 (:error :error)
                 (t :command))))
            tokens)))
(defun highlight-role (span) (highlight-span-role span))
(defun highlight->ansi (spans input theme)
  (declare (ignore theme))
  (let ((result (make-string-output-stream)))
    (let ((pos 0))
          for span in spans
          do (write-string (subseq input pos (highlight-span-start span)) result)
             (case (highlight-span-role span)
               (:command (format result "~C[34m" #\Esc))
               (:operator (format result "~C[33m" #\Esc))
               (:error (format result "~C[31m" #\Esc))
               (t nil))
             (write-string (subseq input (highlight-span-start span)
                                   (highlight-span-end span)) result)
             (format result "~C[0m" #\Esc)
             (setf pos (highlight-span-end span)))
    (write-string (subseq input pos) result)
    (get-output-stream-string result)))
  (get-output-stream-string result)))
