(in-package #:nshell.presentation)
(defun render-prompt (config last-exit)
  (declare (ignore config last-exit))
  (let ((cwd (uiop:getcwd)))
    (format t "~a> " (file-namestring cwd))))
(defun render-input-line (line offset)
  (declare (ignore offset))
  (format t "~a" line))
