(in-package #:nshell.presentation)

(defvar *running* nil)

(defun trampoline (thunk)
  (loop for kont = (funcall thunk) then (funcall kont) while kont))
(defun done () nil)

(defun extract-redirects (args)
  (let ((clean nil) (redirects nil) (i 0))
    (loop while (< i (length args))
          for arg = (nth i args)
          do (cond
               ((string= arg ">") (when (< (1+ i) (length args)) (push (cons :> (nth (1+ i) args)) redirects) (incf i 2)))
               ((string= arg ">>") (when (< (1+ i) (length args)) (push (cons :>> (nth (1+ i) args)) redirects) (incf i 2)))
               ((string= arg "<") (when (< (1+ i) (length args)) (push (cons :< (nth (1+ i) args)) redirects) (incf i 2)))
               (t (push arg clean) (incf i))))
    (values (nreverse clean) (nreverse redirects))))

(defun execute-builtin (ast)
  (let ((cmd (nshell.domain.parsing:command-node-command ast))
        (args (nshell.domain.parsing:command-node-args ast)))
    (cond
      ((string= cmd "echo") (format t "~{~a~^ ~}~%" args) t)
      ((string= cmd "pwd") (format t "~a~%" (uiop:getcwd)) t)
      ((string= cmd "ls") (handler-case (dolist (f (uiop:directory-files (uiop:getcwd))) (format t "~a~%" (file-namestring f))) (error (err) (format t "ls: ~a~%" err))) t)
      ((string= cmd "cd") (when args (handler-case (uiop:chdir (first args)) (error (err) (format t "cd: ~a~%" err)))) t)
      ((string= cmd "exit") (setf *running* nil) t)
      (t nil))))

(defun execute-ast (ast)
  (let* ((cmd (when (nshell.domain.parsing:command-node-p ast)
                (nshell.domain.parsing:command-node-command ast)))
         (args (when cmd (nshell.domain.parsing:command-node-args ast)))
         (redirects nil))
    (when args
      (multiple-value-bind (clean r) (extract-redirects args)
        (setf args clean redirects r)))
    (unwind-protect
         (progn
           (apply-redirects redirects)
           (cond
             ((nshell.domain.parsing:pipeline-node-p ast)
              (nshell.infrastructure.acl:spawn-pipeline
               (nshell.domain.parsing:pipeline-node-commands ast)))
             ((and cmd (let ((cleaned-ast (nshell.domain.parsing:make-command-node cmd args)))
                         (execute-builtin cleaned-ast))))
             ((and cmd) (nshell.infrastructure.acl:run-external cmd args))
             (t (format t "nshell: cannot execute~%"))))
      (nshell.infrastructure.acl:restore-redirects))))

(defun apply-redirects (redirects)
  (dolist (r redirects)
    (let ((op (car r)) (target (cdr r)))
      (case op
        (:> (nshell.infrastructure.acl:redirect-output target :supersede))
        (:>> (nshell.infrastructure.acl:redirect-output target :append))
        (:< (nshell.infrastructure.acl:redirect-input target))))))

(defun read-char-raw () (read-char *standard-input* nil nil))

(defstruct fish-input-state
  (buffer "" :type string)
  (completion-index -1 :type integer)
  (last-candidates nil :type list))

(defun fish-input-loop (history kb config)
  (let ((state (make-fish-input-state)))
    (loop
      (nshell.infrastructure.terminal:ansi-clear-line) (format t "~c" #\Return)
      (render-prompt config nil)
      (let ((text (fish-input-state-buffer state)))
        (handler-case (let ((spans (highlight-line text))) (format t "~a" (highlight->ansi spans text (nshell.domain.configuration:config-theme config)))) (error () (format t "~a" text)))
        (let ((suggestion (compute-suggestion history text)))
          (when (and suggestion (> (length suggestion) 0)) (format t "~C[2m~a~C[0m" #\Esc suggestion #\Esc))))
      (finish-output)
      (let ((ch (read-char-raw)))
        (cond
          ((null ch) (setf *running* nil) (return))
          ((or (char= ch #\Newline) (char= ch #\Return))
           (let ((text (fish-input-state-buffer state)))
             (format t "~%")
             (when (not (string= text ""))
               (handler-case (let ((result (nshell.domain.parsing:parse-command-line text)))
                               (when (nshell.domain.parsing:parse-complete-p result)
                                 (nshell.domain.history:history-add history text)
                                 (nshell.infrastructure.persistence:append-history-entry text)
                                 (execute-ast (nshell.domain.parsing:parse-result-ast result))))
                 (error (err) (format t "nshell error: ~a~%" err)))))
           (return))
          ((char= ch #\Tab)
           (let ((text (fish-input-state-buffer state)))
             (when (> (length text) 0)
               (let* ((candidates (nshell.domain.completion:complete kb text))
                      (cand-texts (mapcar #'nshell.domain.completion:candidate-text candidates))
                      (old-texts (fish-input-state-last-candidates state)))
                 (unless (equal cand-texts old-texts) (setf (fish-input-state-completion-index state) -1 (fish-input-state-last-candidates state) cand-texts))
                 (when candidates
                   (let* ((n (length candidates)) (idx (mod (1+ (fish-input-state-completion-index state)) n)))
                     (setf (fish-input-state-completion-index state) idx (fish-input-state-buffer state) (nth idx cand-texts))
                     (render-completions candidates) (nshell.infrastructure.terminal:ansi-clear-line) (format t "~c" #\Return) (render-prompt config nil) (format t "~a" (fish-input-state-buffer state))))))))
          ((char= ch #\Backspace) (let ((text (fish-input-state-buffer state))) (when (> (length text) 0) (setf (fish-input-state-buffer state) (subseq text 0 (1- (length text)))) (setf (fish-input-state-completion-index state) -1))))
          ((char= (code-char 27) ch) (read-char-raw) (read-char-raw))
          ((char= (code-char 12) ch) (nshell.infrastructure.terminal:ansi-clear-screen))
          ((char= (code-char 3) ch) (format t "^C~%") (setf (fish-input-state-buffer state) "" (fish-input-state-completion-index state) -1))
          ((char= (code-char 4) ch) (let ((text (fish-input-state-buffer state))) (when (string= text "") (setf *running* nil) (return))))
          ((and (>= (char-code ch) 32) (<= (char-code ch) 126)) (setf (fish-input-state-buffer state) (concatenate 'string (fish-input-state-buffer state) (string ch))) (setf (fish-input-state-completion-index state) -1))
          (t nil))))))

(defun run-repl ()
  (setf *running* t)
  (let* ((history (nshell.domain.history:make-command-history))
         (config (nshell.domain.configuration:default-config))
         (kb (nshell.domain.completion:make-knowledge-base)))
    (let ((saved (nshell.infrastructure.persistence:load-history-file)))
      (dolist (entry (reverse saved)) (nshell.domain.history:history-add history entry)))
    (nshell.domain.completion:kb-add-command kb "ls" :flags '("-l" "-a"))
    (nshell.domain.completion:kb-add-command kb "cd") (nshell.domain.completion:kb-add-command kb "echo")
    (nshell.domain.completion:kb-add-command kb "pwd") (nshell.domain.completion:kb-add-command kb "exit")
    (handler-case (nshell.infrastructure.terminal:enable-raw-mode) (error ()))
    (unwind-protect (loop while *running* do (fish-input-loop history kb config))
      (nshell.infrastructure.terminal:restore-terminal-mode) (format t "Goodbye!~%"))))
