(in-package #:nshell.domain.parsing)

(defstruct (token (:constructor make-token (type value &optional (start 0) (end 0))))
  (type :word :type keyword :read-only t)
  (value "" :type string :read-only t)
  (start 0 :type integer :read-only t)
  (end 0 :type integer :read-only t))

(defun token-type (tok) (token-type-val tok))
(defun token-value (tok) (token-value-str tok))
(defun token-start (tok) (token-start-pos tok))
(defun token-end (tok) (token-end-pos tok))

(defun tokenize (input &key (cursor-pos nil))
  (let* ((cp (or cursor-pos (length input)))
         (tokens '())
         (incomplete nil)
         (pos 0)
         (len (length input)))
    (labels ((push-tok (type value start end)
               (push (make-token type value start end) tokens))
             (peek (&optional (offset 0))
               (let ((p (+ pos offset)))
                 (if (< p len) (char input p) nil)))
             (advance (&optional (n 1))
               (incf pos n))
             (read-word ()
               (let ((start pos) (chars '()))
                 (loop while (< pos len)
                       for ch = (peek)
                       while (and (char/= ch #\Space) (char/= ch #\Tab)
                                  (char/= ch #\|) (char/= ch #\>)
                                  (char/= ch #\<) (char/= ch #\#)
                                  (char/= ch #\') (char/= ch #\")
                                  (char/= ch #\\))
                       do (push ch chars) (advance))
                 (push-tok :word (coerce (nreverse chars) 'string) start pos)))
             (read-single-quoted ()
               (let ((start pos) (chars '()))
                 (advance)
                 (loop while (< pos len)
                       for ch = (peek)
                       until (char= ch #\')
                       do (push ch chars) (advance))
                 (if (and (< pos len) (char= (peek) #\'))
                     (progn (advance)
                            (push-tok :word (coerce (nreverse chars) 'string) start pos))
                     (progn (setf incomplete t)
                            (push-tok :error (coerce (nreverse chars) 'string) start pos)))))
             (read-double-quoted ()
               (let ((start pos) (chars '()))
                 (advance)
                 (loop while (< pos len)
                       for ch = (peek)
                       until (char= ch #\")
                       do (if (char= ch #\\)
                              (progn (advance)
                                     (when (< pos len)
                                       (push (peek) chars) (advance)))
                              (progn (push ch chars) (advance))))
                 (if (and (< pos len) (char= (peek) #\"))
                     (progn (advance)
                            (push-tok :word (coerce (nreverse chars) 'string) start pos))
                     (progn (setf incomplete t)
                            (push-tok :error (coerce (nreverse chars) 'string) start pos)))))
             (read-escaped ()
               (advance)
               (when (< pos len)
                 (let ((start (1- pos)))
                   (push-tok :word (string (peek)) start (1+ pos))
                   (advance))))
             (read-comment ()
               (loop while (< pos len)
                     for ch = (peek)
                     until (char= ch #\Newline)
                     do (advance))))
      (loop while (< pos len)
            do (let ((ch (peek)))
                 (cond ((or (char= ch #\Space) (char= ch #\Tab)) (advance))
                       ((char= ch #\|) (push-tok :pipe "|" pos (1+ pos)) (advance))
                       ((and (char= ch #\>) (char= (peek 1) #\>))
                        (push-tok :redirect ">>" pos (+ pos 2)) (advance 2))
                       ((char= ch #\>) (push-tok :redirect ">" pos (1+ pos)) (advance))
                       ((char= ch #\<) (push-tok :redirect "<" pos (1+ pos)) (advance))
                       ((char= ch #\#) (read-comment))
                       ((char= ch #\') (read-single-quoted))
                       ((char= ch #\") (read-double-quoted))
                       ((char= ch #\\) (read-escaped))
                       (t (read-word)))))
      (let ((reversed (nreverse tokens))
            (cursor-tok (find-if (lambda (tok)
                                   (and (>= cp (token-start tok))
                                        (< cp (token-end tok))))
                                 (nreverse tokens))))
        (values reversed cursor-tok incomplete)))))
