(in-package #:nshell.infrastructure.terminal)
(defun ansi-clear-screen () (format t "~C[2J" #\Esc))
(defun ansi-clear-line () (format t "~C[2K" #\Esc))
(defun ansi-move-cursor (row col) (format t "~C[~d;~dH" #\Esc row col))
(defun ansi-set-color (fg &optional bg)
  (format t "~C[3~dm" #\Esc (ansi-color-code fg))
  (when bg (format t "~C[4~dm" #\Esc (ansi-color-code bg))))
(defun ansi-reset () (format t "~C[0m" #\Esc))
(defun ansi-bold () (format t "~C[1m" #\Esc))
(defun ansi-dim () (format t "~C[2m" #\Esc))
(defun ansi-color-code (color)
  (let ((map '(("00FF00" . 2) ("00AFFF" . 4) ("FF0000" . 1) ("FFFF00" . 3)
               ("FFA500" . 3) ("555555" . 8) ("737373" . 8) ("FFFFFF" . 7))))
    (or (cdr (assoc color map :test #'string=)) 7)))
