(in-package #:nshell.infrastructure.terminal)
(defun ansi-clear-screen () (format t "~C[2J" #\Esc))
(defun ansi-clear-line () (format t "~C[2K" #\Esc))
(defun ansi-move-cursor (row col) (format t "~C[~d;~dH" #\Esc row col))
(defun ansi-set-color (fg &optional bg)
  (format t "~C[3~dm" #\Esc (ansi-color-code fg))
  (when bg (format t "~C[4~dm" #\Esc (ansi-color-code bg))))
(defun ansi-reset () (format t "~C[0m" #\Esc))
(defun ansi-bold () (format t "~C[1m" #\Esc))
(defun ansi-dim () (format t "~C[2m" #\Esc))
(defun ansi-save-cursor (&optional (stream *standard-output*))
  (format stream "~C7" #\Esc))
(defun ansi-restore-cursor (&optional (stream *standard-output*))
  (format stream "~C8" #\Esc))
(defun ansi-hide-cursor (&optional (stream *standard-output*))
  (format stream "~C[?25l" #\Esc))
(defun ansi-show-cursor (&optional (stream *standard-output*))
  (format stream "~C[?25h" #\Esc))
(defun ansi-enable-bracketed-paste (&optional (stream *standard-output*))
  (format stream "~C[?2004h" #\Esc))
(defun ansi-disable-bracketed-paste (&optional (stream *standard-output*))
  (format stream "~C[?2004l" #\Esc))
(defun ansi-enable-sgr-mouse (&optional (stream *standard-output*))
  (format stream "~C[?1000h~C[?1006h" #\Esc #\Esc))
(defun ansi-disable-sgr-mouse (&optional (stream *standard-output*))
  (format stream "~C[?1006l~C[?1000l" #\Esc #\Esc))
(defun ansi-enable-alternate-screen (&optional (stream *standard-output*))
  (format stream "~C[?1049h" #\Esc))
(defun ansi-disable-alternate-screen (&optional (stream *standard-output*))
  (format stream "~C[?1049l" #\Esc))
(defun ansi-color-code (color)
  (let ((map '(("00FF00" . 2) ("00AFFF" . 4) ("FF0000" . 1) ("FFFF00" . 3)
               ("FFA500" . 3) ("555555" . 8) ("737373" . 8) ("FFFFFF" . 7))))
    (or (cdr (assoc color map :test #'string=)) 7)))
