(in-package #:nshell.infrastructure.terminal)
(defstruct (screen (:constructor make-screen (&key width height)))
  (width 80 :type integer) (height 24 :type integer) (lines nil :type list))
(defun screen-render (screen content)
  (declare (ignore screen content)) t)
(defun screen-diff (old new)
  (declare (ignore old new))
  (values nil 0))
