(in-package #:nshell.infrastructure.terminal)
(defstruct (screen (:constructor make-screen (&key width height)))
  (width 80 :type integer) (height 24 :type integer) (content "" :type string))
(defun screen-render (screen content)
  (setf (screen-content screen) content)
  (format t "~a" content)
  t)
(defun screen-diff (old new)
  (let ((old-content (screen-content old))
        (new-content (screen-content new)))
    (when (string/= old-content new-content)
      (values (list (cons 0 new-content)) (length new-content)))))
