(in-package #:nshell.infrastructure.persistence)
(defun history-file-path () (merge-pathnames ".nshell_history" (user-homedir-pathname)))
(defun load-history-file ()
  (let ((path (history-file-path)))
    (when (probe-file path)
      (with-open-file (f path :direction :input :if-does-not-exist nil)
        (loop for line = (read-line f nil nil)
              while line collect line)))))
(defun append-history-entry (text)
  (with-open-file (f (history-file-path) :direction :output
                     :if-exists :append :if-does-not-exist :create)
    (format f "~a~%" text)))
(defun vacuum-history (max-entries)
  (declare (ignore max-entries))
  t)
