(in-package #:nshell.domain.configuration)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defstruct (theme (:constructor make-theme (&key (name "default") (colors (make-hash-table :test #'eq)))))
    (name "default" :type string :read-only t)
    (colors (make-hash-table :test #'eq) :type hash-table :read-only t)))
(defun theme-color (theme key) (gethash key (theme-colors theme)))
(defun theme-set-color (theme key value) (setf (gethash key (theme-colors theme)) value) theme)
(defun default-theme ()
  (let ((th (make-theme :name "nshell-default")))
    (dolist (pair '((:normal "00FF00") (:command "00AFFF") (:param "00AFFF")
                    (:comment "737373") (:error "FF0000") (:operator "FFFF00")
                    (:quote "FFA500") (:redirection "00AFFF") (:autosuggestion "555555")
                    (:search-match "FFFF00") (:selection "FFFFFF")
                    (:prompt-host "00AFFF") (:prompt-path "00FF00")
                    (:prompt-error "FF0000") (:prompt-ok "00FF00")))
      (theme-set-color th (car pair) (cdr pair)))
    th))
