(in-package #:nshell.domain.execution)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defstruct (command (:constructor %make-command (name-str args-list))
                      (:conc-name command-))
    (name-str "" :type string :read-only t)
    (args-list nil :type list :read-only t)))
(defun make-command (name &optional args)
  (%make-command name args))
(defun command-name (cmd) (command-name-str cmd))
(defun command-args (cmd) (command-args-list cmd))
(defun command-to-list (cmd)
  (cons (command-name-str cmd) (command-args-list cmd)))
