(in-package #:nshell.domain.execution)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defstruct (job (:constructor %make-job (id-int pipeline-pipe))
                  (:conc-name job-))
    (id-int 0 :type integer :read-only t)
    (pipeline-pipe nil :type (or null pipeline) :read-only t)
    (state-kw :created :type keyword)
    (pgid 0 :type integer)
    (exit-code nil :type (or null integer))
    (pids nil :type list)
    (command-line "" :type string)
    (background-p nil :type boolean)))
(defun make-job (id pipeline) (%make-job id pipeline))
(defun job-id (j) (job-id-int j))
(defun job-state (j) (job-state-kw j))
(defun job-pipeline (j) (job-pipeline-pipe j))
(defun job-state-valid-p (state)
  (not (null (member state '(:created :running :stopped :background :completed :done)))))
(defun job-state-transition (job new-state)
  (unless (job-state-valid-p new-state)
    (error "Invalid job state: ~s" new-state))
  (unless (eq (job-state-kw job) new-state)
    (setf (job-state-kw job) new-state))
  job)
(defun job-running-p (job) (eq (job-state-kw job) :running))
(defun job-stopped-p (job) (eq (job-state-kw job) :stopped))
(defun job-completed-p (job) (eq (job-state-kw job) :completed))
