(in-package #:nshell.domain.execution)
(eval-when (:compile-toplevel :load-toplevel :execute)
  (defstruct (pipeline (:constructor %make-pipeline (commands-list))
                       (:conc-name pipeline-))
    (commands-list nil :type list :read-only t)))
(defun make-pipeline (&rest commands)
  (%make-pipeline commands))
(defun pipeline-commands (pipe) (pipeline-commands-list pipe))
(defun pipeline-single-command-p (pipe) (= (length (pipeline-commands-list pipe)) 1))
(defun pipeline-empty-p (pipe) (null (pipeline-commands-list pipe)))
(defun pipeline-length (pipe) (length (pipeline-commands-list pipe)))
