(in-package #:nshell.domain.completion)
(defun complete (kb partial-input)
  (let ((tokens (nshell.domain.parsing:tokenize partial-input))
        (results '()))
    (declare (ignore tokens))
    (maphash (lambda (name entry)
               (declare (ignore entry))
               (when (and (>= (length name) (length partial-input))
                          (string-equal partial-input name :end2 (length partial-input)))
                 (push (make-candidate name :kind :command) results)))
             (knowledge-base-commands kb))
    (sort results #'string< :key #'candidate-text)))
(defun complete-command (kb prefix)
  (complete kb prefix))
(defun complete-argument (kb cmd-name arg-prefix)
  (declare (ignore kb cmd-name arg-prefix))
  nil)
