(in-package #:nshell.domain.completion)
(defun complete (kb partial-input)
  (let ((results '()))
    (maphash (lambda (name entry)
               (declare (ignore entry))
               (when (and (>= (length name) (length partial-input))
                          (string-equal partial-input name :end2 (length partial-input)))
                 (push (make-candidate name :kind :command) results)))
             (knowledge-base-commands kb))
    (sort results #'string< :key #'candidate-text)))
(defun complete-command (kb prefix) (complete kb prefix))
(defun complete-argument (kb cmd-name arg-prefix)
  (let ((entry (kb-query kb cmd-name)))
    (when entry
      (let ((flags (getf entry :flags)))
        (when flags
          (remove-if-not (lambda (f) (and (>= (length f) (length arg-prefix))
                                          (string-equal arg-prefix f :end2 (length arg-prefix))))
                         flags))))))
