(in-package #:nshell.domain.completion)

(defstruct fact
  (predicate nil :type symbol :read-only t)
  (args '() :type list :read-only t))

(defstruct rule
  (head '() :type list :read-only t)
  (body '() :type list :read-only t))

(defstruct (rule-knowledge-base (:constructor make-rule-knowledge-base (&key (facts nil) (rules nil))))
  (facts nil :type list)
  (rules nil :type list))

(defgeneric predicate-true-p (predicate args bindings)
  (:documentation "Return true when PREDICATE with walked ARGS is true in the current environment."))

(defmethod predicate-true-p ((predicate symbol) args bindings)
  (declare (ignore predicate args bindings))
  nil)

(defun assert-fact! (kb fact)
  (push fact (rule-knowledge-base-facts kb))
  kb)

(defun assert-rule! (kb rule)
  (push rule (rule-knowledge-base-rules kb))
  kb)

(defun logic-variable-symbol-p (x)
  (and (symbolp x)
       (< 0 (length (symbol-name x)))
       (char= #\? (char (symbol-name x) 0))))

(defun variable-name (symbol)
  (subseq (symbol-name symbol) 1))

(defun convert-logic-variables (form env)
  (cond
    ((logic-variable-symbol-p form)
     (or (gethash form env)
         (setf (gethash form env)
               (nshell.domain.parsing:make-var (variable-name form)))))
    ((consp form)
     (cons (convert-logic-variables (car form) env)
           (convert-logic-variables (cdr form) env)))
    (t form)))

(defun fact-head (fact env)
  (convert-logic-variables (cons (fact-predicate fact) (fact-args fact)) env))

(defun rule-head-term (rule env)
  (convert-logic-variables (rule-head rule) env))

(defun rule-body-terms (rule env)
  (mapcar (lambda (goal) (convert-logic-variables goal env))
          (rule-body rule)))

(defun first-proof (kb goal bindings)
  (first (prove-internal kb goal bindings)))

(defun prove-body-with-backtrack (kb goals bindings)
  (nshell.domain.parsing:backtrack
   (mapcar (lambda (goal)
             (lambda (current-bindings)
               (first-proof kb goal current-bindings)))
           goals)
   bindings))

(defun prove-body (kb goals bindings)
  (if (null goals)
      (list bindings)
      (loop for solution in (prove-internal kb (first goals) bindings)
            append (prove-body kb (rest goals) solution))))

(defun prove-built-in-predicate (goal bindings)
  (let* ((predicate (first goal))
         (args (mapcar (lambda (arg) (nshell.domain.parsing:walk arg bindings))
                       (rest goal))))
    (when (predicate-true-p predicate args bindings)
      bindings)))

(defun prove-internal (kb goal bindings)
  (let ((solutions '()))
    (dolist (fact (rule-knowledge-base-facts kb))
      (let ((candidate (nshell.domain.parsing:unify goal (fact-head fact (make-hash-table :test #'eq)) bindings)))
        (when (nshell.domain.parsing:unify-p candidate)
          (push candidate solutions))))
    (dolist (rule (rule-knowledge-base-rules kb))
      (let* ((env (make-hash-table :test #'eq))
             (head (rule-head-term rule env))
             (body (rule-body-terms rule env))
             (head-bindings (nshell.domain.parsing:unify goal head bindings)))
        (when (nshell.domain.parsing:unify-p head-bindings)
          (when (or (null body) (prove-body-with-backtrack kb body head-bindings))
            (setf solutions (append (prove-body kb body head-bindings) solutions))))))
    (or (nreverse solutions)
        (let ((built-in-result (prove-built-in-predicate goal bindings)))
          (when built-in-result (list built-in-result))))))

(defun externalize-bindings (env bindings)
  (let ((result '()))
    (maphash (lambda (symbol var)
               (let ((value (nshell.domain.parsing:walk var bindings)))
                 (unless (nshell.domain.parsing:var-p value)
                   (push (cons symbol value) result))))
             env)
    (nreverse result)))

(defun prove (kb goal &optional (bindings '()))
  (let* ((env (make-hash-table :test #'eq))
         (internal-goal (convert-logic-variables goal env)))
    (mapcar (lambda (solution)
              (externalize-bindings env solution))
            (prove-internal kb internal-goal bindings))))

(defun prove-all (kb goal)
  (prove kb goal '()))

(defun make-built-in-rule-knowledge-base ()
  (let ((kb (make-rule-knowledge-base)))
    (dolist (fact (list (make-fact :predicate 'command-is :args '("cd" "cd"))
                        (make-fact :predicate 'command-is :args '("source" "source"))
                        (make-fact :predicate 'has-flag :args '("ls" "--help"))
                        (make-fact :predicate 'has-flag :args '("git" "--help"))
                        (make-fact :predicate 'git-subcommand :args '("add"))
                        (make-fact :predicate 'git-subcommand :args '("commit"))
                        (make-fact :predicate 'git-subcommand :args '("checkout"))
                        (make-fact :predicate 'git-subcommand :args '("status"))))
      (assert-fact! kb fact))
    (dolist (rule (list (make-rule :head '(suggests-dir ?input)
                                   :body '((command-is ?input "cd")))
                        (make-rule :head '(completes ?cmd "--help")
                                   :body '((has-flag ?cmd "--help")))
                        (make-rule :head '(completes "git" ?sub)
                                   :body '((git-subcommand ?sub)))
                        (make-rule :head '(suggests-file ?input)
                                   :body '((command-is ?input "source")))))
      (assert-rule! kb rule))
    kb))

(defparameter *built-in-rule-knowledge-base* (make-built-in-rule-knowledge-base))
