(in-package #:nshell.application)
(defstruct (event-dispatcher (:constructor make-event-dispatcher ()))
  (subscribers (make-hash-table :test #'eq) :type hash-table)
  (queue nil :type list))
(defun publish-event (dispatcher event)
  (push event (event-dispatcher-queue dispatcher))
  event)
(defun subscribe (dispatcher event-type handler)
  (push handler (gethash event-type (event-dispatcher-subscribers dispatcher) nil)))
(defun drain-events (dispatcher)
  (let ((events (nreverse (event-dispatcher-queue dispatcher))))
    (setf (event-dispatcher-queue dispatcher) nil)
    (dolist (event events)
      (let ((handlers (gethash (nshell.domain.events:domain-event-type event)
                               (event-dispatcher-subscribers dispatcher))))
        (dolist (handler handlers)
          (funcall handler event))))))
