(in-package #:nshell.application)
(defvar *job-monitor* (nshell.domain.job-control:make-job-monitor))
(defun fg (job-id) (nshell.domain.job-control:foreground-job *job-monitor* job-id))
(defun bg (job-id) (nshell.domain.job-control:resume-job *job-monitor* job-id))
(defun jobs () (nshell.domain.job-control:monitor-jobs *job-monitor*))
(defun interrupt-foreground ()
  (format t "~%Interrupt~%"))
(defun suspend-foreground ()
  (format t "~%Suspended~%"))
